sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/news/index.md
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/news/index.html
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/news/index.html
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/articles/*md
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/articles/*html
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/llms.txt
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/authors.md
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/sitemap.xml
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/index.md
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/docs/search.json
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/DESCRIPTION
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/pkgdown/index.md
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/README.md
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/HARMONIC_FORMAT/GO_BB/HARMONIC_PREPROCESSING.R
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/HARMONIC_FORMAT/GO_BB/HARMONIC_PREPROCESSING_OLD.R
sed -i 's/HARMONIC/HARMONIC/g' /data3/psg/NGS_2026/gitHARMONIC/HARMONIC_FORMAT/GO_BB/HARMONIC_PREPROCESSING_onlyREG.R
