---
title: "Single-case preprocessing & analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Single-case analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{css, echo=FALSE}
pre {
  margin-top: 0.8rem;
  margin-bottom: 1.6rem;
}

.sourceCode {
  margin-bottom: 1.6rem;
}
```
## R code

### 1. Load the HARMONIC R package
```{r, results='hide'}
# install.packages("remotes")
# remotes::install_github("ERASMUSlab/HARMONIC")

# For exact reproducibility, pin clusterProfiler to the validated version:
# install.packages("./clusterProfiler_4.14.6.tar.gz",
#                  repos = NULL,
#                  type  = "source")

library(haRmonic)
packageVersion("clusterProfiler")
```

```{r, echo=FALSE, comment=""}
# install.packages("remotes")
# remotes::install_github("ERASMUSlab/HARMONIC")

# For exact reproducibility, pin clusterProfiler to the validated version:
# install.packages("./clusterProfiler_4.14.6.tar.gz",
#                  repos = NULL,
#                  type  = "source")

library(haRmonic)
packageVersion("clusterProfiler")
```

### 2. Preprocessing & Analysis
```{r, eval=FALSE}
HARMONIC_ANALYSIS(filepath = "../HARMONIC_DIFF/HARMONIC/",
                  type = "standard",
                  full_condition = c("DAY0","DAY4","DAY7","DAY10","DAY14","DAY21"),
                  number_of_rep = c(3, 3, 3, 6, 3, 3),
                  DEG_list_name = "input_DEG_list.txt",
                  mango_design = c("DAY4_DAY0_UP"),
                  core = 1,
                  ref_genome = "mm",
                  PASSED_RATIO = 20,
                  PASSED_NUM = 2,
                  similarity = 70,
                  preprocessing = "T")
```

### 3. Modificate parameters
```{r, eval=FALSE}
HARMONIC_ANALYSIS(filepath = "../HARMONIC_DIFF/HARMONIC/",
                  type = "standard",
                  full_condition = c("DAY0","DAY4","DAY7","DAY10","DAY14","DAY21"),
                  number_of_rep = c(3, 3, 3, 6, 3, 3),
                  DEG_list_name = "input_DEG_list.txt",
                  mango_design = c("DAY4_DAY0_UP"),
                  core = 1,
                  ref_genome = "mm",
                  PASSED_RATIO = 20,
                  PASSED_NUM = 3,
                  similarity = 50,
                  preprocessing = "F")
```

